prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix test: <http://www.w3.org/2000/10/rdf-tests/rdfcore/testSchema#>
		
select distinct ?input (?input as ?result) (?input as ?name) {
	?input a test:NT-Document.
} order by ?input