prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix test: <http://www.w3.org/2000/10/rdf-tests/rdfcore/testSchema#>
		
select ?input ?result (?test_case as ?name) ?descr {
	?test_case a test:PositiveParserTest;
		test:outputDocument ?result;
		test:inputDocument ?input;
		test:status ?status;
		a ?type.
	optional {?test_case test:description ?descr}
	filter (?status != "OBSOLETE" && ?status != "NOT_APPROVED")
	filter (!regex(str(?test_case), "0031")) # @reverse is not supported atm
	filter (!regex(str(?test_case), "0036")) # work in progress
	filter (!regex(str(?test_case), "0037")) # work in progress
	filter (!regex(str(?test_case), "0038")) # work in progress
} order by ?input