prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix test: <http://www.w3.org/2000/10/rdf-tests/rdfcore/testSchema#>
		
select ?input ?result (?test_case as ?name) ?descr {
	?test_case a test:PositiveParserTest;
		test:outputDocument ?result;
		test:inputDocument ?input;
		test:status ?status;
		a ?type.
	optional {?test_case test:description ?descr}
	filter (?status != "OBSOLETE" && ?status != "NOT_APPROVED")

	# known bugs
	filter (!regex(str(?test_case), "toRdf_0035"))
	filter (!regex(str(?test_case), "toRdf_0048"))
	filter (!regex(str(?test_case), "toRdf_0059"))
	filter (!regex(str(?test_case), "toRdf_0060"))
	filter (!regex(str(?test_case), "toRdf_0061"))
	filter (!regex(str(?test_case), "toRdf_0064"))
	filter (!regex(str(?test_case), "toRdf_0065"))
	filter (!regex(str(?test_case), "toRdf_0068"))
	filter (!regex(str(?test_case), "toRdf_0069"))
	filter (!regex(str(?test_case), "toRdf_007[1-4]"))
	filter (!regex(str(?test_case), "toRdf_007[6-9]"))
	filter (!regex(str(?test_case), "toRdf_0083"))
	filter (!regex(str(?test_case), "toRdf_0085"))
	filter (!regex(str(?test_case), "toRdf_0088"))
	filter (!regex(str(?test_case), "toRdf_0089"))
	filter (!regex(str(?test_case), "toRdf_009[1-9]"))
	filter (!regex(str(?test_case), "toRdf_010[0-2]"))
	filter (!regex(str(?test_case), "toRdf_010[5-8]"))
	filter (!regex(str(?test_case), "toRdf_0111"))
	filter (!regex(str(?test_case), "toRdf_0112"))

    # @container = @language is not supported yet
	filter (!regex(str(?test_case), "toRdf_0070"))
	filter (!regex(str(?test_case), "toRdf_0075"))

    # @set is not supported yet
	filter (!regex(str(?test_case), "toRdf_0044"))
	filter (!regex(str(?test_case), "toRdf_0047"))
	filter (!regex(str(?test_case), "toRdf_0054"))
	filter (!regex(str(?test_case), "toRdf_0055"))
	filter (!regex(str(?test_case), "toRdf_0056"))
	filter (!regex(str(?test_case), "toRdf_0063"))
	filter (!regex(str(?test_case), "toRdf_0067"))
	filter (!regex(str(?test_case), "toRdf_0087"))
	filter (!regex(str(?test_case), "toRdf_0090"))

    # @index is not supported yet
	filter (!regex(str(?test_case), "toRdf_0080"))
	filter (!regex(str(?test_case), "toRdf_0084"))
	filter (!regex(str(?test_case), "toRdf_0103"))
} order by ?input